In [10]:
import pandas as pd

df = pd.DataFrame({
    "area": [1000, 1500, None, 2500],
    "price": [8_000_000, 12_000_000, 16_000_000, 20_000_000]
})

df["area"] = df["area"].fillna(df["area"].median())

print(df)

     area     price
0  1000.0   8000000
1  1500.0  12000000
2  1500.0  16000000
3  2500.0  20000000


In [9]:
import numpy as np

X = np.array([1, 2, 3, 4, 5], dtype=float)
y = np.array([2, 4, 6, 8, 10], dtype=float)

w = 0.0
b = 0.0
learning_rate = 0.01
epochs = 1000

m = len(X)

for epoch in range(epochs):

    y_pred = w * X + b
    errors = y_pred - y

    cost = np.sum(errors ** 2) / (2 * m)

    dw = np.sum(errors * X) / m
    db = np.sum(errors) / m

    w -= learning_rate * dw
    b -= learning_rate * db

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Cost: {cost:.4f}")
print("Final weight:", w)
print("Final bias:", b)

Epoch 0, Cost: 22.0000
Epoch 100, Cost: 0.0172
Epoch 200, Cost: 0.0122
Epoch 300, Cost: 0.0087
Epoch 400, Cost: 0.0062
Epoch 500, Cost: 0.0044
Epoch 600, Cost: 0.0032
Epoch 700, Cost: 0.0023
Epoch 800, Cost: 0.0016
Epoch 900, Cost: 0.0011
Final weight: 1.9737548787242036
Final bias: 0.09475321533750963


In [15]:
from sklearn.linear_model import LinearRegression 

# Features
# [area, bedrooms, age]

X = np.array ([
    [1000, 2, 10],
    [1500, 3, 5],
    [2000, 4, 3],
    [2500, 4, 2],
    [3000, 5, 1],
])

y  = np.array([200, 300, 400, 500, 600])

model = LinearRegression()

model.fit(X, y)

print ("Intercept:", model.intercept_)
print ("Coefficients:", model.coef_)

new_house = [[2200, 4, 4]]

prediction = model.predict(new_house)

print("Prediction price:", prediction)
    

Intercept: -1.1368683772161603e-13
Coefficients: [2.00000000e-01 7.48965402e-15 2.24697647e-14]
Prediction price: [440.]


In [17]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split 

X = np.array([
    [1000, 2, 10],
    [1200, 2, 8],
    [1500, 3, 5],
    [1700, 3, 4],
    [2000, 4, 3],
    [2200, 4, 3],
    [2500, 4, 2],
    [2800, 5, 2],
    [3000, 5, 1],
    [3500, 5, 1],
])

y = np.array([200, 240, 300, 340, 400, 440, 500, 560, 600, 700])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Prediction:", y_pred)
print("Actual:", y_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2:", r2_score(y_test, y_pred))

Prediction: [600. 240.]
Actual: [600 240]
MAE: 1.7053025658242404e-13
RMSE: 1.797546735911271e-13
R2: 1.0


In [21]:
X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6],
])

y = np.array([
    2,
    5,
    10,
    17,
    26,
    37
])
linear_model = LinearRegression()
linear_model.fit(X,y)

print(linear_model.predict([[7]]))

[40.66666667]


In [24]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)

print(X_poly)

[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]
 [ 1.  6. 36.]]


In [53]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# 1. Define data
X = np.array([[1], [2], [3], [4], [5], [6]])
y = np.array([2, 5, 10, 17, 26, 37])  # Follows pattern: y = x^2 + 1

# 2. Create and apply PolynomialFeatures (degree 2 fits this quadratic pattern)
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

# 3. Train linear regression on polynomial features
model = LinearRegression()
model.fit(X_poly, y)

# 4. Predict for new value
new_X = [[7]]
new_X_poly = poly.transform(new_X)
prediction = model.predict(new_X_poly)

print("Prediction:", prediction[0])

Prediction: 50.00000000000002


In [25]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6],
])

y = np.array([
    2,
    5,
    10,
    17,
    26,
    37
])

model = Pipeline([
    ("polynomial", PolynomialFeatures(degree = 2)),
    ("linear", LinearRegression())
])

model.fit(X,y)

prediction = model.predict([[10]])
print(prediction)

[50.]


In [37]:
from sklearn.linear_model import LogisticRegression
X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6],
    [7],
    [8],
    [9],
    [10],
])

y = np.array([
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
])

model = LogisticRegression()

model.fit(X, y)
prediction = model.predict([[7]])
print(prediction)

probability = model.predict_proba([[7]])

print(probability)

[1]
[[0.14439923 0.85560077]]


In [6]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X, y)
new_customer = [[42, 75, 4]]
prediction = model.predict(new_customer)
print(prediction)


[1]


In [7]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)
import numpy as np

X = np.array ([
    [20, 30, 1],
    [25, 40, 2],
    [30, 50, 2],
    [35, 60, 3],
    [40, 70, 4],
    [45, 80, 5],
    [50, 90, 6],
    [55, 100, 7],
])


y = np.array([
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
])

# 1. Generate predictions
y_pred = model.predict(X_test)  # or model.predict(X) depending on your split

# 2. Calculate and print metrics
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

ValueError: X has 4 features, but LogisticRegression is expecting 3 features as input.

In [3]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

iris = load_iris()

X = iris.data
y = iris.target

print(X.shape)
print(y.shape)

print(iris.target_names)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

model = LogisticRegression(max_iter=200)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

(150, 4)
(150,)
['setosa' 'versicolor' 'virginica']
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Accuracy: 1.0


In [9]:
new_flower = [[5.1, 3.5, 1.4, 0.2]]

prediction = model.predict(new_flower)

print(prediction)

predicted_class = model.predict(new_flower)[0]

predicted_class_name = iris.target_names[predicted_class_index]

# 2. Get class probabilities
probabilities = model.predict_proba(new_flower)[0]

print(probabilities)

ValueError: X has 4 features, but LogisticRegression is expecting 3 features as input.